# Generated by Django 3.1.1 on 2020-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
