# Generated by Django 3.1.1 on 2020-09-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_goods_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='modelGoods',
        ),
    ]
