# Generated by Django 3.1.1 on 2020-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0003_auto_20200909_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgoods',
            name='discription',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelgoods',
            name='price',
            field=models.CharField(default=10000, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelgoods',
            name='image',
            field=models.URLField(),
        ),
    ]
